/**
 * POST /api/queue/promote — promote a resource into the queue.
 *
 *   ┌──────────────────────────────────────────────────────────────────┐
 *   │  Body: { resource_id }                                           │
 *   │                                                                  │
 *   │  For verdict='keep':                                             │
 *   │    1. Sonnet generates {why_now, lesson_plan} for THIS resource  │
 *   │       given the user's current capability map.                   │
 *   │    2. Insert queue_items with status='queued'.                   │
 *   │                                                                  │
 *   │  For verdict='not_yet':                                          │
 *   │    The user can still promote — the resource's existing Haiku    │
 *   │    lesson_plan is inherited (those are the lead-up lessons).     │
 *   │    why_now is generated by Sonnet too.                           │
 *   │                                                                  │
 *   │  For other verdicts (skip, already_have, needs_review):          │
 *   │    Reject with 400 — promote only makes sense from keep/not_yet. │
 *   └──────────────────────────────────────────────────────────────────┘
 *
 * SSE stream so the user sees Sonnet generation progress (1-3s typical).
 */

import { withSession } from '@/lib/auth'
import { db, schema } from '@/lib/db/client'
import { eq, sql } from 'drizzle-orm'
import { type Capability, type Theme } from '@/lib/taxonomy'
import { generateLessonPlan } from '@/lib/llm/sonnet-lesson-plan'
import type { LessonStep } from '@/lib/db/schema'

export const runtime = 'nodejs'
export const maxDuration = 120

type PromoteEvent =
  | { type: 'started'; verdict: string }
  | { type: 'generating_lesson_plan' }
  | {
      type: 'ready'
      queue_item_id: number
      why_now: string
      lesson_plan: LessonStep[]
      sonnet_dropped: number
    }
  | { type: 'error'; message: string }

function frame(e: PromoteEvent): string {
  return `event: ${e.type}\ndata: ${JSON.stringify(e)}\n\n`
}

type Body = { resource_id?: number }

export const POST = withSession(async (req) => {
  const body = (await req.json().catch(() => ({}))) as Body
  const stream = new ReadableStream<Uint8Array>({
    async start(controller) {
      const enc = new TextEncoder()
      const send = (e: PromoteEvent) => controller.enqueue(enc.encode(frame(e)))

      try {
        const resourceId = body.resource_id
        if (typeof resourceId !== 'number') {
          send({ type: 'error', message: 'resource_id required' })
          return
        }
        const rows = await db
          .select()
          .from(schema.resources)
          .where(eq(schema.resources.id, resourceId))
          .limit(1)
        const resource = rows[0]
        if (!resource) {
          send({ type: 'error', message: 'resource not found' })
          return
        }
        if (
          resource.verdict !== 'keep' &&
          resource.verdict !== 'not_yet'
        ) {
          send({
            type: 'error',
            message: `cannot promote a ${resource.verdict} item`,
          })
          return
        }
        // Already in queue?
        const existing = await db
          .select()
          .from(schema.queueItems)
          .where(eq(schema.queueItems.resourceId, resourceId))
          .limit(1)
        if (existing[0]) {
          send({
            type: 'error',
            message: 'this item is already in your queue',
          })
          return
        }
        send({ type: 'started', verdict: resource.verdict })

        const capsTaught = (resource.capabilitiesTaught as Capability[]) ?? []
        const primaryTheme: Theme | null = capsTaught[0]?.theme ?? null

        let whyNow: string
        let lessonPlan: LessonStep[]
        let sonnetDropped = 0

        if (resource.verdict === 'not_yet') {
          // Inherit Haiku's lead-up lesson_plan. Generate fresh why_now via Sonnet.
          send({ type: 'generating_lesson_plan' })
          // Load user caps + library for Sonnet prompt context.
          const userCaps = await loadUserCapabilities()
          const library = await loadAvailableLibrary(resource.id)
          try {
            const result = await generateLessonPlan({
              resource: {
                id: resource.id,
                title: deriveTitle(resource.url, resource.contentText),
                url: resource.url,
                contentText: resource.contentText,
                capabilitiesTaught: capsTaught,
              },
              userCapabilities: userCaps,
              availableLibrary: library,
            })
            // For not_yet: keep Haiku's lead-up plan, take only the why_now.
            whyNow = result.whyNow
            lessonPlan =
              (resource.lessonPlan as LessonStep[] | null)?.length
                ? (resource.lessonPlan as LessonStep[])
                : result.lessonPlan
            sonnetDropped = result.droppedCount
          } catch (err) {
            console.warn('[promote] Sonnet failed:', err)
            whyNow = 'Closes a gap in your capability map.'
            lessonPlan =
              ((resource.lessonPlan as LessonStep[] | null) ?? []) as LessonStep[]
          }
        } else {
          // verdict === 'keep' — Sonnet generates fresh {why_now, lesson_plan}.
          send({ type: 'generating_lesson_plan' })
          const userCaps = await loadUserCapabilities()
          const library = await loadAvailableLibrary(resource.id)
          try {
            const result = await generateLessonPlan({
              resource: {
                id: resource.id,
                title: deriveTitle(resource.url, resource.contentText),
                url: resource.url,
                contentText: resource.contentText,
                capabilitiesTaught: capsTaught,
              },
              userCapabilities: userCaps,
              availableLibrary: library,
            })
            whyNow = result.whyNow
            lessonPlan = result.lessonPlan
            sonnetDropped = result.droppedCount
          } catch (err) {
            console.warn('[promote] Sonnet failed:', err)
            whyNow = "Couldn't generate lesson plan."
            lessonPlan = []
          }
        }

        const inserted = await db
          .insert(schema.queueItems)
          .values({
            resourceId: resource.id,
            status: 'queued',
            primaryTheme,
            whyNow,
            lessonPlan,
            // rank_score will be filled in by Step 6 / re-rank.
            rankScore: 0,
          })
          .returning({ id: schema.queueItems.id })

        send({
          type: 'ready',
          queue_item_id: inserted[0].id,
          why_now: whyNow,
          lesson_plan: lessonPlan,
          sonnet_dropped: sonnetDropped,
        })
      } catch (err) {
        send({
          type: 'error',
          message: err instanceof Error ? err.message : 'unknown error',
        })
      } finally {
        controller.close()
      }
    },
  })

  return new Response(stream, {
    headers: {
      'content-type': 'text/event-stream',
      'cache-control': 'no-cache, no-transform',
      connection: 'keep-alive',
      'x-accel-buffering': 'no',
    },
  })
})

async function loadUserCapabilities(): Promise<Capability[]> {
  const rows = await db
    .select({
      theme: schema.capabilities.theme,
      name: schema.capabilities.name,
      status: schema.capabilities.status,
    })
    .from(schema.capabilities)
  return rows
    .filter((r) => r.status === 'have' || r.status === 'partial')
    .map((r) => ({ theme: r.theme as Theme, name: r.name }))
}

async function loadAvailableLibrary(
  excludeId: number,
): Promise<Array<{ id: number; title: string }>> {
  const rows = await db
    .select({
      id: schema.resources.id,
      url: schema.resources.url,
      contentText: schema.resources.contentText,
      verdict: schema.resources.verdict,
    })
    .from(schema.resources)
    .where(
      sql`${schema.resources.id} <> ${excludeId} AND ${schema.resources.verdict} IN ('keep', 'already_have')`,
    )
    .limit(30)
  return rows.map((r) => ({
    id: r.id,
    title: deriveTitle(r.url, r.contentText),
  }))
}

function deriveTitle(url: string | null, contentText: string): string {
  if (url) {
    try {
      const u = new URL(url)
      return `${u.hostname}${u.pathname}`.slice(0, 100)
    } catch {
      return url.slice(0, 100)
    }
  }
  return contentText.split('\n')[0]?.slice(0, 100) ?? 'Untitled'
}
